# Generated by Django 3.2.4 on 2021-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('f_name', models.CharField(max_length=150, verbose_name='Female name')),
                ('abv_conselho', models.CharField(default='None', max_length=150, verbose_name='Abrev. Conselho')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Nome')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('is_enabled', models.BooleanField(verbose_name='isEnabled')),
                ('role', models.IntegerField(verbose_name='ID role')),
                ('uf_conselho', models.CharField(default='None', max_length=100, verbose_name='UF Conselho')),
                ('cod_conselho', models.CharField(default=0, max_length=120, verbose_name='Código conselho')),
            ],
        ),
    ]
