# Generated by Django 3.2.4 on 2021-08-01 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('num', models.IntegerField(default=0, verbose_name='Número atendimento')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando atendimento'), ('triagem', 'Triado'), ('consultorio', 'Consultado'), ('encerrado', 'Encerrado')], default='aguardando', max_length=30, verbose_name='Status')),
                ('moment_triagem', models.DateTimeField(blank=True, null=True, verbose_name='Momento da triagem')),
                ('moment_consultorio', models.DateTimeField(blank=True, null=True, verbose_name='Momento da consulta')),
                ('moment_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Momento do encerramento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FichaHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Nº Ficha')),
            ],
        ),
        migrations.CreateModel(
            name='VitalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('temperature', models.FloatField(verbose_name='Temperatura corporal')),
                ('pas', models.IntegerField(verbose_name='Sístole')),
                ('pad', models.IntegerField(verbose_name='Diástole')),
                ('saturation', models.IntegerField(verbose_name='Saturação')),
                ('heart_beats', models.IntegerField(verbose_name='Batimentos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='PB', max_length=2, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('department', models.CharField(default='azul', max_length=30, verbose_name='Setor')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Atendimento', to='core.attendance')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responsável', to=settings.AUTH_USER_MODEL)),
                ('vital_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vitais', to='core.vitaldata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='core.patient'),
        ),
    ]
