# Generated by Django 3.2.4 on 2021-06-30 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=140, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('cns', models.CharField(max_length=20, verbose_name='CNS')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='cod_conselho',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uf_conselho',
        ),
        migrations.AddField(
            model_name='user',
            name='conselho',
            field=models.CharField(default=0, max_length=120, verbose_name='Conselho'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='isEnabled'),
        ),
    ]
