# Generated by Django 3.2.4 on 2021-07-03 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210630_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': ('Paciente',), 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': ('Cargo',), 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('Usuário',), 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='abv_conselho',
        ),
        migrations.RemoveField(
            model_name='role',
            name='rank',
        ),
        migrations.AddField(
            model_name='patient',
            name='adress',
            field=models.CharField(default='', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(default=models.CharField(max_length=300, verbose_name='Password'), max_length=300, verbose_name='Re_Password'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('biom', 'Biomédico/Biomédica'), ('bioq', 'Bioquímico/Bioquímica'), ('enf', 'Enfermeiro/Enfermeira'), ('med', 'Médico/Médica'), ('dig', 'Digitador/Digitadora'), ('rec', 'Recepcionista'), ('farm', 'Farmacêutico/Farmacêutica'), ('tec', 'Técnico'), ('coord', 'Coordenador/Coordenadora'), ('dir', 'Diretor/Diretora')], max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Cargo'),
        ),
    ]
