# Generated by Django 3.2.4 on 2021-08-22 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210807_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendances', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='department',
        ),
        migrations.AddField(
            model_name='triagem',
            name='description',
            field=models.TextField(default='', max_length=800, verbose_name='Descrição dos sintomas'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Moderada'), (2, 'Alta')], default=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='creation_hour',
            field=models.TimeField(default=datetime.time(9, 29, 7, 666299), verbose_name='Hora da criação'),
        ),
        migrations.AlterField(
            model_name='vitaldata',
            name='pad',
            field=models.IntegerField(verbose_name='Pressão diástolica'),
        ),
        migrations.AlterField(
            model_name='vitaldata',
            name='pas',
            field=models.IntegerField(verbose_name='Pressão sistólica'),
        ),
    ]
