# Generated by Django 3.2.4 on 2021-07-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210702_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('Funcionário',), 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='role',
            name='cod',
            field=models.CharField(choices=[('biom', 'Biomédico/Biomédica'), ('bioq', 'Bioquímico/Bioquímica'), ('enf', 'Enfermeiro/Enfermeira'), ('med', 'Médico/Médica'), ('dig', 'Digitador/Digitadora'), ('rec', 'Recepcionista'), ('farm', 'Farmacêutico/Farmacêutica'), ('tec', 'Técnico'), ('coord', 'Coordenador/Coordenadora'), ('dir', 'Diretor/Diretora')], default='invalid', max_length=20, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino'), ('o', 'Outro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='f_name',
            field=models.CharField(max_length=150, verbose_name='Feminino'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Masculino'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino'), ('o', 'Outro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Está habilitado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='re_password',
            field=models.CharField(default='', max_length=300, verbose_name='Confirmação da senha'),
        ),
    ]
