# Generated by Django 3.2.4 on 2021-08-26 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210825_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='creation_hour',
            field=models.TimeField(default=datetime.time(21, 8, 29, 174818), verbose_name='Hora da criação'),
        ),
        migrations.AlterField(
            model_name='attendancequeue',
            name='attendances',
            field=models.JSONField(default={'attendances': []}),
        ),
    ]
