# Generated by Django 3.2.4 on 2021-08-26 00:11

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210825_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='creation_hour',
            field=models.TimeField(default=datetime.time(21, 11, 18, 155469), verbose_name='Hora da criação'),
        ),
        migrations.AlterField(
            model_name='attendancequeue',
            name='attendances',
            field=models.JSONField(default=core.models.get_default_queue),
        ),
    ]
