# Generated by Django 3.2.4 on 2022-06-20 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210825_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagem',
            options={'verbose_name': 'Triagem', 'verbose_name_plural': 'Triagens'},
        ),
        migrations.AlterModelOptions(
            name='vitaldata',
            options={'verbose_name': 'Dados vitais', 'verbose_name_plural': 'Dados vitais'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='creation_hour',
            field=models.TimeField(default=datetime.time(20, 50, 17, 620550), verbose_name='Hora da criação'),
        ),
    ]
