# Generated by Django 3.2.4 on 2022-07-24 20:44

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220627_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sign_attendance',
            field=models.CharField(default='', max_length=400, verbose_name='Assinatura atendimento'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sign_triagem',
            field=models.CharField(default='', max_length=400, verbose_name='Assinatura triagem'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='creation_hour',
            field=models.TimeField(default=datetime.time(17, 44, 44, 690789), verbose_name='Hora da criação'),
        ),
        migrations.AlterField(
            model_name='attendancequeue',
            name='attendances',
            field=jsonfield.fields.JSONField(blank=True, default='[]'),
        ),
    ]
