# Generated by Django 3.2.4 on 2022-07-27 00:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220724_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sign_triagem',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='triage_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Triagem', to='core.triagem'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='creation_hour',
            field=models.TimeField(default=datetime.time(21, 53, 50, 410561), verbose_name='Hora da criação'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavem_triagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='vital_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Vitais', to='core.vitaldata'),
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('order', models.TextField(max_length=5000, verbose_name='Solicitação')),
                ('was_released', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Liberado')], default=0, verbose_name='Status')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_medicacao', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitante_medicacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de medicamento',
                'verbose_name_plural': 'Solicitações de medicamento',
            },
        ),
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('order', models.TextField(max_length=5000, verbose_name='Solicitação')),
                ('was_released', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Liberado')], default=0, verbose_name='Status')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_exame', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitante_exame', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de exame',
                'verbose_name_plural': 'Solicitações de exames',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='exams_orders',
            field=models.ManyToManyField(blank=True, related_name='exames', to='core.ExamOrder'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='medication_orders',
            field=models.ManyToManyField(blank=True, related_name='medicamentos', to='core.MedicationOrder'),
        ),
    ]
