# Generated by Django 3.2.4 on 2021-07-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
